### ISSUE TITLE
purple end portal frames not working

### ISSUE THREAD

**Issue by Fjorde** [LittleImprovementsCustom/LittleImprovementsCustom#127]
when purple end portal frames is selected the texture does not show up in game as the texture is not in the pack assets folder

**Comment by Beatso** [comment]
could you please send the contents of your selectedModules.txt?

**Comment by Fjorde** [comment]
[selectedModules.txt](https://github.com/LittleImprovementsCustom/LittleImprovementsCustom/files/5661797/selectedModules.txt)

**Comment by Beatso** [comment]
Purple End Portal Frame is not selected in your selectedModules.txt. Upload your pack to the site, and try to select purple end portal frame. If something goes wrong then, let me know :)

**Comment by Beatso** [comment]
after our discussion on discord: try downloading a pack with all 3 purple end packs only, and let me know what you get. the purple end eyes should merge with the end portal frame, which works fine for me.

**Comment by Fjorde** [comment]
yes it works fine with just those three packs
