### ISSUE TITLE
Emmisive_ores and variated ores are not showing that it is incompatible

### ISSUE THREAD

**Issue by bjorn-beatso** [LittleImprovementsCustom/LittleImprovementsCustom#173]
> This issue was created by an automation. It was authored in Discord by Nigelrex#8452, in Beatso's Server #feedback-support.

**Comment by Nigelrex** [comment]
![image](https://user-images.githubusercontent.com/75080457/107840673-ccba6d80-6dda-11eb-8d07-a863321ea7d9.png)

**Comment by Beatso** [comment]
They are compatible. Selecting both will give you a merged pack with emissive variated ores.
