### ISSUE TITLE
Variated fungi doesn't show it's image

### ISSUE THREAD

**Issue by bjorn-beatso** [LittleImprovementsCustom/LittleImprovementsCustom#194]
> This issue was created by an automation. It was authored in Discord by Nigelrex#8452, in Beatserver #lounge.

**Comment by Beatso** [comment]
fixed in https://github.com/LittleImprovementsCustom/LittleImprovementsCustom/commit/daa16813b9951c5a96c13652eabdcaa63001d1f2
