### ISSUE TITLE
Pack is not downloading

### ISSUE THREAD

**Issue by Fjorde** [LittleImprovementsCustom/LittleImprovementsCustom#36]
After selecting the packs I wished to download and pressing download, I waited over a minute and a half of the website being frozen with no pack download even commencing. I tried this multiple times with the same result. Reloading the page did not help either.

**Comment by Beatso1** [comment]
What browser are you using?

**Comment by Fjorde** [comment]
I am using the latest version of Google Chrome.

**Comment by Beatso1** [comment]
There were a number of errors that later got fixed. Could you try again (maybe with just one or two modules selected) please?
If it fails, do you get an error message in the bottom right of your screen?

**Comment by Fjorde** [comment]
Ok one minute please

**Comment by Fjorde** [comment]
Ah it seems to be working with just one item

**Comment by Fjorde** [comment]
When I previously selected around 12 it took a very long time and I thought it was a bug with the website

**Comment by Beatso1** [comment]
I think everything should be working now. Let me know if you have any more issues :)
