### ISSUE TITLE
Add merged pack between daggers and alternativeNetheriteTools

### ISSUE THREAD

**Issue by Beatso** [LittleImprovementsCustom/LittleImprovementsCustom#55]
needs a merged texture for netherite sword

**Comment by Beatso** [comment]
Textures that need merging:
https://github.com/LittleImprovementsCustom/LittleImprovementsCustom/blob/master/storage/modules/daggers/textures/item/netherite_sword.png
https://github.com/LittleImprovementsCustom/LittleImprovementsCustom/blob/master/storage/modules/alternativeNetheriteTools/textures/item/netherite_sword.png

**Comment by Fjorde** [comment]
working on it

**Comment by Beatso** [comment]
@Fjorde to create merged texture
@Beatso to complete adding of merged module, including lang and modules.json
