### ISSUE TITLE
lecternBottom model still uses oak_planks as bottom texture

### ISSUE THREAD

**Issue by Beatso** [LittleImprovementsCustom/LittleImprovementsCustom#81]
https://github.com/LittleImprovementsCustom/LittleImprovementsCustom/blob/8901ac60379664724796e678673b1f68bb2455ad/storage/modules/lecternBottom/models/block/lectern.json#L5

Originally reported by iloveflareon on discord

**Comment by Daggsy** [comment]
Oak planks textures needs to be in lectern model, because in other way we have carpet in weird place.
