### ISSUE TITLE
move better sign icons to fixes

### ISSUE THREAD

**Issue by bjorn-discord** [LittleImprovementsCustom/LittleImprovementsCustom#86]
would make more sense since it's making them more like block
up to you to make the change though, feel free to close this issue and leave in aesthetic :)
originally suggested by @CoolixerBlitz on discord

> This issue was created by an automation. It was authored in Discord by Beatso#1815, in Beatso's Resource Packs #support.

**Comment by Beatso** [comment]
fixed in https://github.com/LittleImprovementsCustom/LittleImprovementsCustom/commit/8396ffcc9c1639a3c54836a4228ec102b1031f5e
